app = 'shachilog'
primary_region = 'nrt'
kill_signal = "SIGINT"
kill_timeout = 5
# processes = [ ]
swap_size_mb = 512

[experimental]
allowed_public_ports = [ ]
auto_rollback = true
  enable_consul = true

# [build]

[[mounts]]
  source = 'data'
  destination = '/data'

[[services]]
  internal_port = 8080
  processes = ['app']
  protocol = "tcp"
  script_checks = [ ]
  # force_https = true
  # auto_stop_machines = true
  # auto_start_machines = true
  # min_machines_running = 0

  [services.concurrency]
    hard_limit = 100
    soft_limit = 80
    type = "requests"
    
  [[services.ports]]
    handlers = [ "http" ]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = [ "tls", "http" ]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 6

  #  [[services.http_checks]]
  #   interval = "10s"
  #   timeout = "5s"
  #   grace_period = "1m0s"
  #   restart_limit = 0
  #   method = "get"
  #   path = "/api/healthcheck"
  #   protocol = "http"

    
   [[services.http_checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/litefs/health"

  